# See configuration options: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "npm" # Specifies the package manager
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly" # Frequency of update checks
    commit-message:
      prefix: "fix" # Prefix for commit messages
    open-pull-requests-limit: 5 # Limit of open pull requests
  - package-ecosystem: "pip" # Additional example for Python
    directory: "/path/to/requirements" # Location of pip manifests
    schedule:
      interval: "weekly" # Weekly checks
    commit-message:
      prefix: "fix" # Prefix for commit messages
    open-pull-requests-limit: 5 # Similar limit
